require("Raul.plugins-setup")
require("Raul.core.options")
require("Raul.core.keymaps")
require("Raul.core.colorscheme")
require("Raul.plugins.comment")
require("Raul.plugins.nvim-tree")
require("Raul.plugins.lualine")
require("Raul.plugins.telescope")
